name: Build
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check me out
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v2

      - name: Build the report
        run: |
          npm ci
          npm run build --if-present

      - name: Upload to somewhere
        run: echo TODO
      

